apiVersion: v1
data:
  METADATA_GRPC_SERVICE_HOST: metadata-grpc-service.kubeflow
  METADATA_GRPC_SERVICE_PORT: "8080"
kind: ConfigMap
metadata:
  annotations:
    metacontroller.k8s.io/last-applied-configuration: '{"apiVersion":"v1","data":{"METADATA_GRPC_SERVICE_HOST":"metadata-grpc-service.kubeflow","METADATA_GRPC_SERVICE_PORT":"8080"},"kind":"ConfigMap","metadata":{"labels":{"controller-uid":"c0449912-8ce8-4750-86e6-092322771dac"},"name":"metadata-grpc-configmap","namespace":"test-tpu"}}'
  creationTimestamp: "2024-07-22T19:18:20Z"
  labels:
    controller-uid: c0449912-8ce8-4750-86e6-092322771dac
  name: metadata-grpc-configmap
  namespace: test-tpu
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: false
    controller: true
    kind: Namespace
    name: test-tpu
    uid: c0449912-8ce8-4750-86e6-092322771dac
  resourceVersion: "4847363"
  uid: 93c45519-d763-49d2-96cf-c1d5a683818b
