apiVersion: kubeflow.org/v1alpha1
kind: PodDefault
metadata:
  name: access-tensorboard-s3-role
  namespace: {{ .Values.PROJECT_NAME }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.ROLE_ARN }}
spec:
  desc: Allow access S3 for tensorboard
  selector:
    matchLabels:
      tb-s3-config: "true"
  env:
    - name: AWS_REGION
      value: ca-central-1
    - name: AWS_ROLE_ARN
      value: {{ .Values.ROLE_ARN }}
    - name: AWS_WEB_IDENTITY_TOKEN_FILE
      value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    - name: AWS_STS_REGIONAL_ENDPOINTS
      value: regional
    - name: AWS_DEFAULT_REGION
      value: ca-central-1
  serviceAccountName: default-editor
  volumes:
    - name: aws-iam-token
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              path: token
              expirationSeconds: 86400
              audience: sts.amazonaws.com
  volumeMounts:
    - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
      name: aws-iam-token
      readOnly: true